#!/bin/bash

musicDir=/mnt/syno/Music
albumDir=$musicDir/$(mpc current -f "[%albumartist%|%artist%]/%album%/" | sed 's/^ //' | sed 's/ \//\//g')
cover=$(find "$albumDir" | grep -i cover\.jpg)

## Butt-ugly quick fix to prevent multiplying windows ##
#killall nsxiv

if xwininfo -name nsxiv > /dev/null ; then
	WID=$(xwininfo -name nsxiv | grep xwininfo | cut -d ' ' -f 4)

	## Display album art ##
	nsxiv -g 600x600 -bqe $WID "$cover"
else
	nsxiv -g 600x600 -bq "$cover"
fi

