#!/bin/bash

theme=$(cat ~/.local/share/flavours/lastscheme)
head -n -2 ~/.config/cava/config > ~/.cache/config_test

colors=$(
	cat .local/share/flavours/base16/schemes/wesanderson/$theme.yaml |
	awk -F '"' '{print "#" $2}' 
	)

echo $colors | 
awk -F ' ' '{print "gradient_color_1 = " "\""$20"\"" " \ngradient_color_2 = " "\""$21"\""}' >> ~/.cache/config_test

command mv ~/.cache/config_test ~/.config/cava/config
