#!/bin/sh

# Arbitrary but unique message id
msgId="991049"

if [ $# -eq 0 ]; then
pamixer -t > /dev/null
else
pactl set-sink-volume @DEFAULT_SINK@ $1 > /dev/null
fi

volume=$(pamixer --get-volume-human)
mute=$(pamixer --get-mute)

if [[ "$mute" == "true" ]]; then
    # Show the sound muted notification
    dunstify -a "changeVolume" -i $HOME/scripts/img/mute.png -r "$msgId" "Volume muted" 
else

# Show the volume notification
    dunstify -a "changeVolume" -i $HOME/scripts/img/up.png -r "$msgId" \
    -h int:value:"$volume" "Volume: ${volume}"
fi

# Play the volume changed sound
#canberra-gtk-play -i audio-volume-change -d "changeVolume"
