#!/bin/fish

curl -s https://corona-stats.online/NO |sed  's/\x1b\[[0-9;]*m//g' > ~/.cache/corona

set countn (grep "Norway" ~/.cache/corona |
	sed "s/\s*//g ; s/║//g ; s/│/;/g ; s/\n//" |
	awk -F';' '{print $2 " 🤢" $3 "("$4")" "💀 " $5 }')

set countw (grep "World" ~/.cache/corona |
	sed "s/\s*//g ; s/║//g ; s/│/;/g ; s/\n//" |
	awk -F';' '{print $2 " 🤢" $3 "("$4")" "💀 " $5 }')

notify-send -i $HOME/Pictures/virus.png -t 50000 "$countn
$countw"
