#! /bin/sh

[ -z "$1" ] && printf "Give me when (year) and where (continent)!\n" && exit

link=$"https://www.davidrumsey.com/luna/servlet/view/all/where/$2/when/$1?"

curl -s "$link" |
	grep 'RUMSEY~8~1~' | 
	awk -F '~' '{print $4 "~" $5}' | 
	grep -o "[0-9]*~[0-9]*"|
	uniq -d |
	sort -u > $XDG_CACHE_HOME/rumlist

# For each map/id in the list returned by previous command (loop)
while IFS= read -r id;
do
	# Creating vars and writing to bibfile 
	curl -s "https://www.davidrumsey.com/luna/servlet/detail/RUMSEY~8~1~$id" > $XDG_CACHE_HOME/rum
	
	author=$(sed -n '/>author</{N; p}' $XDG_CACHE_HOME/rum | sed 's/<[^>]\+>/ /g' | grep -v "author" | sed 's/^\s\+//' | sed 's/\s*$//' | sed "s/&#039;/\'/g" | xargs -0) 
	
	date=$(sed -n '/>date</{N; p}' $XDG_CACHE_HOME/rum | sed 's/<[^>]\+>/ /g' | grep -v "date" | sed 's/\s\+//g')
	
	pdate=$(sed -n '/>pub_date</{N; p}' $XDG_CACHE_HOME/rum | sed 's/<[^>]\+>/ /g' | grep -v "date" | sed 's/\s\+//g')
	
	publisher=$(sed -n '/>publisher</{N; p}' $XDG_CACHE_HOME/rum | sed 's/<[^>]\+>/ /g' | grep -v "publisher" | sed 's/^\s\+//' | sed 's/\s*$//' | sed "s/amp;/\&/g" | sed "s/&#039;/\'/g" | xargs -0)
	
	location=$(sed -n '/>publisher_location</{N; p}' $XDG_CACHE_HOME/rum | sed 's/<[^>]\+>/ /g' | grep -v "location" | sed 's/^\s\+//' | sed 's/\s*$//' | sed "s/&#039;/\'/g")
	
	title=$(sed -n '/>short_title</{N; p}' $XDG_CACHE_HOME/rum | sed 's/<[^>]\+>/ /g' | grep -v "title" | sed 's/^\s\+//' | sed 's/\s*$//' | sed "s/&#039;/\'/g")
	
	key=$(printf "$author" | sed -n '1p' | sed 's/\s\+//g' | awk -v var="$date" -F ',' '{print $1var}')

while grep -qo "{$key," $HOME/work/Legacies/map.bib ; do 
	key=$(printf "$key""I\n")
done
	
	 printf "@misc{$key, 
	 date = $pdate,
	 title = {$title},
	 author = {$author},
	 note = {$date},
	 publisher = {$publisher},
	 address = {$location},
	 url = {https://www.davidrumsey.com/luna/servlet/detail/RUMSEY~8~1~$id}
 	}\n\n" | tee -a $HOME/work/Legacies/map.bib
	
	if cat $XDG_CACHE_HOME/rum | grep -qo "[A-Z0-9]*/[A-Z0-9]*\.sid" ; then
		#download sid
		did=$(cat $XDG_CACHE_HOME/rum | grep -o "[A-Z0-9]*/[A-Z0-9]*\.sid" | 
			sort -u | sed s'/\.sid//') 
		curl -s "https://rumseysid.lunaimaging.com/mrsid/mrsid_images/Rumsey/SIDS/$did.jp2?image=/$did.sid" > "$HOME/work/Legacies/maps/$key.sid"
	else 
		did=$(cat $XDG_CACHE_HOME/rum |
			grep -o "[A-Z0-9]*/[A-Z0-9]*\.jp2" | 
			sort -u | sed s'/\.jp2//')
		#download jp2
		curl -s "https://www.davidrumsey.com/static/jp2k/$did.jp2" > "$HOME/work/Legacies/maps/$key.jp2"
	fi
	
done < "$XDG_CACHE_HOME/rumlist"

