#!/bin/sh

# Setting date for comment
date=$(date)

# Ignoring files exeeding githubs 100M limit
# and printing the currently ignored large files
find * -size +100M | cat >> .gitignore
find * -size +100M

# Adding and commiting everything
git add -A
git commit -am "$date"

# Finding branch
branch=$(git branch --show-current)

# Pushing to current branch
git push origin $branch
