#!/bin/sh

# Setting date for comment
date=$(date)

# Ignoring files exeeding githubs 100M limit
# and printing the currently ignored large files
find * -size +100M | cat >> .gitignore
find * -size +100M

# Finding branch
branch=$(git branch --show-current)

# Pulling for changes to remote
git pull origin $branch

# Adding and commiting everything
git add -A
git commit -am "$date"

# Pushing to current branch
git push origin $branch
