#!/bin/sh
[ -z "$1" ] && echo "Give either a pdf file or a DOI as an argument." && exit

if [ -f "$1" ]; then
	# Try to get DOI from pdfinfo or pdftotext output.
	doi=$(pdfinfo "$1" | grep -io "doi:.*") ||
	doi=$(pdftotext "$1" 2>/dev/null - | grep -io "doi:.*" -m 1) ||
	exit 1
else
	doi="$1"
fi

# Check crossref.org for the bib citation.
curl -s "http://api.crossref.org/works/$doi/transform/application/x-bibtex" -w "\\n" > .cache/bibref

cat .cache/bibref >> work/lib.bib

# Reformatting to refer
sed 's/[{}]//g' .cache/bibref | 
sed 's/,$//'|
sed 's/^[\t]//'|
sed 's/^year =/\%D/'|
sed 's/^publisher =/\%I/'|
sed 's/^volume =/\%V/'|
sed 's/^number =/\%N/'|
sed 's/^pages =/\%P/'|
sed 's/^title =/\%T/'|
sed 's/^journal =/\%J/'|
sed 's/^editor =/\%E/'|
sed 's/^adress =/\%C/'|
grep ^% > .cache/ref

grep '\author =' .cache/bibref | sed 's/^[\t]//;s/[{}]//g;s/,$//;s/author = /\%A /;s/ and /\n\%A /g' >> .cache/ref

cat .cache/ref >> work/referlib

echo 'I wrote this to the bib:'
cat .cache/bibref
read -r -p "Would you like to edit this? [y/N] " response
case "$response" in
    [yY][eE][sS]|[yY]) 
	$EDITOR work/lib.bib
        ;;
    *)
        
        ;;
esac

echo 'I wrote this to refer:' 
cat .cache/ref
read -r -p "Would you like to edit this? [y/N] " response
case "$response" in
    [yY][eE][sS]|[yY]) 
	$EDITOR work/referlib
        ;;
    *)
        
        ;;
esac
