#!/bin/sh
# Provide a folder containing .Heic or .heif files

[ -z "$1" ] 

for f in $(find "$1" -iregex '.*.\(HEIC\|heif\)' -type f)
do
echo "Working on file $f"
heif-convert $f $f.jpg
done

notify-send "Done! :)"
