#! /bin/bash

[ -z "$1" ]

jan=$"01"
feb=$"02"
mar=$"03"
apr=$"04"
mai=$"05"
jun=$"06"
jul=$"07"
aug=$"08"
sep=$"09"
okt=$"10"
nov=$"11"
des=$"12"

month=$(exiv2 $1 | grep timestamp | awk -F ':' '{print $3}')

if [ "$month" == "$jan" ]; then
	cp  -vn $1 /home/mariussw/Synology/Bilder/2021/01Januar/
fi

if [ "$month" == "$feb" ]; then
	cp  -vn $1 /home/mariussw/Synology/Bilder/2021/02Februar/
fi

if [ "$month" == "$mar" ]; then
	cp  -vn $1 /home/mariussw/Synology/Bilder/2021/03Mars/
fi

if [ "$month" == "$apr" ]; then
	cp  -vn $1 /home/mariussw/Synology/Bilder/2021/04April/
fi

if [ "$month" == "$mai" ]; then
	cp  -vn $1 /home/mariussw/Synology/Bilder/2021/05Mai/
fi

if [ "$month" == "$jun" ]; then
	cp  -vn $1 /home/mariussw/Synology/Bilder/2021/06Juni/
fi


if [ "$month" == "$jul" ]; then
	cp  -vn $1 /home/mariussw/Synology/Bilder/2021/07Juli/
fi


if [ "$month" == "$aug" ]; then
	cp  -vn $1 /home/mariussw/Synology/Bilder/2021/08August/
fi


if [ "$month" == "$sep" ]; then
	cp  -vn $1 /home/mariussw/Synology/Bilder/2021/09September/
fi


if [ "$month" == "$okt" ]; then
	cp  -vn $1 /home/mariussw/Synology/Bilder/2021/10Oktober/
fi


if [ "$month" == "$nov" ]; then
	cp  -vn $1 /home/mariussw/Synology/Bilder/2021/11November/
fi


if [ "$month" == "$des" ]; then
	cp  -vn $1 /home/mariussw/Synology/Bilder/2021/12Desember/
fi
