#!/bin/bash

# Get user selection via dmenu from bib file.
chosen=$(ls $HOME/work/Library/ | rofi -dmenu -i -l 30 )

# Exit if none chosen.
[ -z "$chosen" ] && exit

# open in zathura
zathura $HOME/work/Library/$chosen
