#!/bin/bash

MUSIC_DIR=$HOME/Music/
path=$MUSIC_DIR$(mpc current -f %albumartist%/%album%/)

ext=$(ls "$path" | grep -x ^cover.*)

COVER=$path$ext

notify-send "$(mpc --format '%artist% \n- \n%title%' current)" -i "$COVER" -t 5000
