#!/bin/bash

musicDir=/mnt/syno/Music
albumpath=$musicDir/$(mpc current -f "[%albumartist%|%artist%]/%album%/" | sed 's/^ //' | sed 's/ \//\//g')

coverext=$(ls "$albumpath" | grep "^cover.*")

COVER=$albumpath$coverext

magick "$COVER" -resize 125x "/tmp/cover.$coverext"

notify-send "$(mpc --format '%artist% \n- \n%title%' current)" -i "/tmp/cover.$coverext" -t 5000
