#!/bin/bash

# Set library folder

lib="/home/mariussw/ARC_Project Dropbox/Marius Wishman/Apps/Overleaf/TJ-project/Literature/"

# Look up doi/link at sci-hub
sci=$(curl "https://sci-hub.se/$1" | grep -m1 pdf | awk -F "'" '{print $2}')

# Create a sensable file name
ck=$(printf $sci | awk -F '?' '{print $1}' | grep -o "[a-zA-Z0-9]*\.pdf")

# Download
if printf $sci | grep sci-hub ; then
	curl "https:/$sci" > "$lib$ck"
else
	curl "https:/sci-hub.se$sci" > "$lib$ck"
fi

# Is the filename ok?
read -r -p "Is this: $ck, a good filename? [y/n]" response
case "$response" in
	[yY])
		;;
	*)
		printf "Input new filename!"
		read new
		mv "$lib$ck"  "$lib$new"
		;;
esac
