#!/bin/bash

# Startup script

# Set recursive rate
xset r rate 300 50

# Set caps lock to function as escape
setxkbmap -option caps:escape

# Run i3-auto-layout and leave it running
i3-auto-layout &
