#!/bin/sh

curl -s 'https://www.morningstar.no/no/funds/snapshot/snapshot.aspx?id=F00000JORS&tab=1' | sed 's/<[^>]\+>/ /g' | grep '1 dag' > ~/.cache/stonks

curl -s 'https://www.morningstar.no/no/funds/snapshot/snapshot.aspx?id=F00000MKDH&tab=1' | sed 's/<[^>]\+>/ /g' | grep '1 dag' >> ~/.cache/stonks

dnb=$(sed -n '1p' ~/.cache/stonks | awk -F' ' '{print $5"%"}' )

klp=$(sed -n '2p' ~/.cache/stonks | awk -F' ' '{print $5"%"}' )

notify-send -i /usr/share/icons/oxygen/base/32x32/actions/office-chart-line-stacked.png -t 10000 "DNB Global Indeks A $dnb
KLP Fremvoksende Markeder Indeks II $klp"
