#!/bin/bash

curl -s 'https://www.morningstar.no/no/funds/snapshot/snapshot.aspx?id=F00000JORS&tab=1' | sed 's/<[^>]\+>/ /g' | grep '1 dag' > ~/.cache/stonks

curl -s 'https://www.morningstar.no/no/funds/snapshot/snapshot.aspx?id=F00000MKDH&tab=1' | sed 's/<[^>]\+>/ /g' | grep '1 dag' >> ~/.cache/stonks

dnb=$(sed -n '1p' ~/.cache/stonks | awk -F' ' '{print $5"%"}' )

klp=$(sed -n '2p' ~/.cache/stonks | awk -F' ' '{print $5"%"}' )

echo "DNB: $dnb KLP: $klp "
