#!/bin/bash

ddnb=$(sed -e 's/,/./g' -ne '1p' ~/.cache/stonks | awk -F' ' '{print $5}')

dklp=$(sed -e 's/,/./g' -ne '2p' ~/.cache/stonks | awk -F' ' '{print $5}')

total=$(sed -n '3p' ~/.cache/cash)

echo "DNB: $ddnb% KLP: $dklp%"
