#!/bin/sh

# Arbitrary but unique message id
msgId="991049"

#if [ $# -eq 0 ]; then
#pulseaudio-ctl mute > /dev/null
#else
#pactl set-sink-volume @DEFAULT_SINK@ $1 > /dev/null
echo $1
#fi

#volume=$(pulseaudio-ctl full-status | awk '{print $1}')
#mute=$(pulseaudio-ctl full-status | awk '{print $2}')

#if [[ $volume == 0 || "$mute" == "yes" ]]; then
    # Show the sound muted notification
#    dunstify -a "changeVolume" -i audio-volume-muted -r "$msgId" "Volume muted" 
#else

# Show the volume notification
#    dunstify -a "changeVolume" -i audio-volume-high -r "$msgId" \
#    -h int:value:"$volume" "Volume: ${volume}%"
#fi

# Play the volume changed sound
#canberra-gtk-play -i audio-volume-change -d "changeVolume"
