#!/bin/sh

wal -a 80 -i $HOME/Pictures/wal2/*
xrandr --output DP1-2 --auto --left-of eDP1
feh --bg-scale $HOME/Pictures/wal2/*
#xwallpaper --screen 0 --zoom $HOME/Pictures/wal2/*
Sripts/startup
$HOME/.config/polybar/launch.sh
picom -b
