#! /bin/bash

echo "Please input a range of years separeated by a space, 
followed by a region/location:"

read fyear tyear location

echo $location

# Formatting location	
location=$(echo $location | sed -e 's/^./\U&/g; s/ ./\U&/g' | sed 's/ /\+/g')

# Loop over the supplied years for the given region
for i in $(seq $fyear $tyear); 
	do downrum $i $location;
done

# Notify that it is done
curl \
-H "Tags: heavy_check_mark" \
-d "Download script is done" ntfy.sh/projectlegacyntfy
