#!/bin/zsh

if [ $# -eq 0 ]; then
team="Arsenal"
else
team=$1
fi

LiveScores $team &

#echo " Out of the loop"

#find .cache/LiveScores/$team | entr -s 'notify-send -i "$HOME/Pictures/football.png" -t 5000 "$(cat .cache/LiveScores/$team)"'

while inotifywait -e attrib .cache/LiveScores/$team; do notify-send -i "$HOME/Pictures/football.png" -t 5000 "$(cat .cache/LiveScores/$team)"; done
